resolver: nightly-2022-03-25

packages:
- .

extra-deps:
- capability-0.5.0.1

flags:
  avail:
    capability: true
    exceptions: true
    monad-control: true
    mtl: true
    primitive: true
    semigroupoids: true
    unliftio: true

ghc-options:
  "$everything": -haddock
