resolver: lts-14.27

packages:
- .

flags:
  avail:
    capability: false
    exceptions: true
    monad-control: true
    mtl: true
    primitive: true
    semigroupoids: true
    unliftio: false

ghc-options:
  "$everything": -haddock
